#!/usr/bin/env python3
"""Builds the executive and technical slide decks (.pptx) from the figures
in docs/figures/ (generated by generate_deliverable_assets.py) and the
same numbers reported by the training pipeline, never hand-typed
separately from what the pipeline actually measured.

Usage: python scripts/build_slides.py
Outputs to deliverables/ (gitignored, these are submission artifacts,
not repository content).
"""

from __future__ import annotations

from pathlib import Path

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches, Pt

from pdm.config import REPO_ROOT, load_config
from pdm.models.bundle import BUNDLE_FILENAME, ModelBundle

FIGURES = REPO_ROOT / "docs" / "figures"
OUT_DIR = REPO_ROOT.parent / "deliverables"
OUT_DIR.mkdir(parents=True, exist_ok=True)

NAVY = RGBColor(0x1F, 0x3A, 0x5F)
GRAY = RGBColor(0x4A, 0x4A, 0x4A)
ACCENT = RGBColor(0x55, 0xA8, 0x68)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)

SLIDE_W, SLIDE_H = Inches(13.333), Inches(7.5)


def new_deck() -> Presentation:
    prs = Presentation()
    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H
    return prs


def blank_slide(prs: Presentation):
    return prs.slides.add_slide(prs.slide_layouts[6])


def add_title(slide, text: str, size: int = 32, color=NAVY, top=Inches(0.4)) -> None:
    box = slide.shapes.add_textbox(Inches(0.6), top, SLIDE_W - Inches(1.2), Inches(1.0))
    tf = box.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = text
    p.font.size = Pt(size)
    p.font.bold = True
    p.font.color.rgb = color


def add_subtitle(slide, text: str, top=Inches(1.2), size=18, color=GRAY) -> None:
    box = slide.shapes.add_textbox(Inches(0.6), top, SLIDE_W - Inches(1.2), Inches(0.6))
    p = box.text_frame.paragraphs[0]
    p.text = text
    p.font.size = Pt(size)
    p.font.color.rgb = color


def add_bullets(slide, items: list[str], top=Inches(1.5), left=Inches(0.6), width=None, size=18) -> None:
    width = width or (SLIDE_W - Inches(1.2))
    box = slide.shapes.add_textbox(left, top, width, SLIDE_H - top - Inches(0.4))
    tf = box.text_frame
    tf.word_wrap = True
    for i, item in enumerate(items):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.text = f"•  {item}"
        p.font.size = Pt(size)
        p.font.color.rgb = GRAY
        p.space_after = Pt(10)


def add_picture_centered(slide, path: Path, top=Inches(1.5), max_height=Inches(5.5)) -> None:
    if not path.exists():
        return
    pic = slide.shapes.add_picture(str(path), Inches(0), top, height=max_height)
    pic.left = int((SLIDE_W - pic.width) / 2)


def title_slide(prs, title: str, subtitle: str) -> None:
    slide = blank_slide(prs)
    slide.background.fill.solid()
    slide.background.fill.fore_color.rgb = NAVY
    box = slide.shapes.add_textbox(Inches(0.8), Inches(2.6), SLIDE_W - Inches(1.6), Inches(1.5))
    p = box.text_frame.paragraphs[0]
    p.text = title
    p.font.size = Pt(40)
    p.font.bold = True
    p.font.color.rgb = WHITE
    box2 = slide.shapes.add_textbox(Inches(0.8), Inches(4.0), SLIDE_W - Inches(1.6), Inches(1.0))
    p2 = box2.text_frame.paragraphs[0]
    p2.text = subtitle
    p2.font.size = Pt(20)
    p2.font.color.rgb = RGBColor(0xCC, 0xD6, 0xE0)


def content_slide(prs, title: str, bullets: list[str], subtitle: str | None = None) -> None:
    slide = blank_slide(prs)
    add_title(slide, title)
    top = Inches(1.2)
    if subtitle:
        add_subtitle(slide, subtitle)
        top = Inches(1.8)
    add_bullets(slide, bullets, top=top)


def figure_slide(prs, title: str, figure_name: str, caption: str | None = None) -> None:
    slide = blank_slide(prs)
    add_title(slide, title, size=26)
    add_picture_centered(slide, FIGURES / figure_name, top=Inches(1.1))
    if caption:
        box = slide.shapes.add_textbox(Inches(0.6), SLIDE_H - Inches(0.6), SLIDE_W - Inches(1.2), Inches(0.5))
        p = box.text_frame.paragraphs[0]
        p.text = caption
        p.font.size = Pt(13)
        p.font.italic = True
        p.font.color.rgb = GRAY
        p.alignment = PP_ALIGN.CENTER


def build_executive_deck(bundle: ModelBundle) -> None:
    prs = new_deck()
    m = bundle.metrics

    title_slide(
        prs,
        "Manutenção Preditiva: Motor Elétrico",
        "Prévia técnica e proposta de projeto  |  SENAI SC  |  Processo Seletivo 02485/2026",
    )

    content_slide(
        prs, "O que este projeto entrega",
        [
            "Um modelo que identifica o estado operacional do motor a partir dos sensores já instalados",
            "Um sistema que avisa quando não tem confiança suficiente, em vez de arriscar um palpite",
            "Uma arquitetura completa (API + banco de dados + dashboard) já prototipada e testada",
            "Um cronograma de 9 meses até o piloto validado em produção, com riscos mapeados",
        ],
    )

    figure_slide(
        prs, "A auditoria de dados encontrou problemas reais, e os tratamos",
        "sensor_audit_verdict.png",
        "2 dos 5 sensores fornecidos foram excluídos com teste estatístico antes de qualquer modelo ser treinado.",
    )

    figure_slide(
        prs, "O resultado é real, não sorte nem vazamento de dados",
        "sanity_controls.png",
        "Controles de sanidade (rótulos embaralhados, sensor de ruído isolado) caem para o nível do acaso, como deveriam.",
    )

    content_slide(
        prs, "Resultado da prévia",
        [
            f"F1-macro em teste (nunca visto): {m.get('test_f1_macro', float('nan')):.1%}",
            f"Erro de calibração esperado (ECE): {m.get('test_ece', float('nan')):.3f} (as probabilidades reportadas são confiáveis)",
            f"Cobertura de predição conformal: {m.get('conformal_coverage', float('nan')):.1%} (alvo: 90%)",
            "O sistema já sabe dizer 'não tenho certeza' em vez de sempre arriscar uma resposta",
        ],
    )

    figure_slide(
        prs, "Matriz de confusão: onde o modelo acerta e onde hesita",
        "confusion_matrix.png",
    )

    content_slide(
        prs, "Arquitetura proposta",
        [
            "Auditoria de dados -> limpeza -> engenharia de features -> modelo interpretável -> predição com incerteza",
            "API de inferência + banco de dados de predições/auditoria/drift + dashboard para o time de manutenção",
            "O banco de dados de vocês continua sendo a fonte da verdade: não duplicamos o histórico bruto de sensores",
        ],
        subtitle="Detalhes completos em docs/03_arquitetura.md",
    )

    figure_slide(prs, "Cronograma proposto: 9 meses até o piloto validado", "gantt_chart.png")

    content_slide(
        prs, "Riscos mapeados: e a maioria já mitigada em código",
        [
            "Dados insuficientes ou requisitos não definidos a tempo -> track de pesquisa com datasets públicos em paralelo",
            "Sensores em falha em produção -> auditoria automática re-executa a cada novo lote",
            "Modelo desatualizando com o tempo -> monitoramento de drift já implementado",
            "Resistência de adoção pelo time de manutenção -> explicabilidade por predição, não caixa-preta",
        ],
    )

    content_slide(
        prs, "Próximos passos",
        [
            "Reunião de kick-off com automação, manutenção e TI (Fase 0, mês 1)",
            "Definição conjunta da semântica de cada estado/classe da máquina",
            "Acesso de leitura ao banco de dados já existente",
            "Aprovação da proposta e início da Fase 0",
        ],
    )

    prs.save(str(OUT_DIR / "Apresentacao_Executiva.pptx"))
    print(f"wrote {OUT_DIR / 'Apresentacao_Executiva.pptx'}")


def build_technical_deck(bundle: ModelBundle) -> None:
    prs = new_deck()
    m = bundle.metrics

    title_slide(
        prs,
        "Manutenção Preditiva: Motor Elétrico",
        "Apresentação técnica  |  Pipeline, dados, modelagem, avaliação e arquitetura",
    )

    content_slide(
        prs, "Interpretação do problema",
        [
            "Dois papéis: arquiteto/mentor do projeto contratado + autor de uma prévia técnica que convença o diretor",
            "Ceticismo como método: auditar os dados antes de confiar neles, não depois",
            "docs/01_interpretacao_problema.md",
        ],
    )

    figure_slide(prs, "Balanceamento de classes: curado, não representativo de produção", "class_balance.png")

    content_slide(
        prs, "O que a auditoria de dados encontrou",
        [
            "Dados_1, Dados_2, Dados_3: sinal real, discriminam as classes (Kruskal-Wallis + permutação de MI)",
            "Dados_4: travado em valor quase constante (sensor morto/mal cabeado)",
            "Dados_5: estatisticamente indistinguível de ruído branco em relação às classes",
            "Coluna 201 em Dados_1-3: artefato de exportação, quase inteiramente vazia, descartada com validação",
            "5 classes perfeitamente balanceadas, padrão que não ocorre numa planta real",
        ],
    )

    figure_slide(prs, "Auditoria de sensores por informação mútua com a classe", "sensor_audit_verdict.png")

    content_slide(
        prs, "Pipeline de engenharia de features",
        [
            "Tempo: RMS, curtose, fator de crista/forma/impulso/clearance, zero-crossing",
            "Frequência: bandas de 250 Hz, centróide espectral, entropia, flatness, picos dominantes",
            "Wavelet: energia por escala (CWT Morlet, PyWavelets), ridge synchrosqueezed quando disponível",
            "Limpeza: filtro de Hampel para saturação, interpolação de NaN, flag de janela silenciosa",
            "Limiares de limpeza ajustados só no split de treino, nunca vazam para calibração/teste",
        ],
    )

    figure_slide(
        prs, "Wavelet na prática: energia concentrada em bandas por classe", "wavelet_scalogram.png",
        "Escalograma CWT (Morlet) real de uma janela por classe; a base da feature de energia por escala.",
    )

    content_slide(
        prs, "Seleção de modelo",
        [
            "4 candidatos comparados por validação cruzada estratificada: árvore de decisão, Random Forest, HistGradientBoosting, XGBoost",
            f"Vencedor: {bundle.model_name}",
            f"F1-macro médio em CV: {m.get('cv_f1_macro_mean', float('nan')):.4f} (+/- {m.get('cv_f1_macro_std', float('nan')):.4f})",
            "Sem deep learning: regime de dados não justifica, e trocaria interpretabilidade por ganho marginal",
        ],
    )

    figure_slide(prs, "Matriz de confusão em teste (nunca visto no treino)", "confusion_matrix.png")

    figure_slide(prs, "Calibração de probabilidade", "calibration.png",
                 "ECE baixo é pré-requisito para a predição conformal fazer sentido.")

    figure_slide(prs, "Predição conformal: tamanho do conjunto de predição", "conformal_set_sizes.png")

    content_slide(
        prs, "Reavaliação sob desbalanceamento realista",
        [
            "O conjunto do case está artificialmente balanceado (10k janelas/classe)",
            "evaluation/imbalance.py reamostra o teste sob um prior configurável (operação saudável dominante)",
            "Recall e PR-AUC por classe reportados sob esse prior, não só no cenário balanceado",
        ],
    )

    figure_slide(prs, "Robustez: degradação ao remover um sensor", "robustness_sensor_dropout.png")

    figure_slide(prs, "Controles de sanidade: o resultado não é vazamento", "sanity_controls.png")

    content_slide(
        prs, "Explicabilidade",
        [
            "Importância por permutação: sempre disponível, qualquer estimador",
            "SHAP (TreeExplainer): explicabilidade global e local, real nesta execução",
            "LIME: explicação local por instância, sempre disponível",
            "Árvore de decisão como baseline totalmente legível",
        ],
    )

    figure_slide(prs, "Arquitetura do sistema", "architecture_overview.png")

    figure_slide(prs, "Pipeline de treino em detalhe", "pipeline_detail.png")

    content_slide(
        prs, "API, banco de dados e disponibilização",
        [
            "FastAPI: /predict, /predict_batch, /explain, /audit, /drift, /health",
            "SQLite local / Postgres via Docker, armazena só o que a IA produz (predições, auditorias, drift)",
            "Dashboard Streamlit para o time de manutenção",
            "Demonstração completa em notebooks/03_api_demo.ipynb",
        ],
    )

    content_slide(
        prs, "Dependências opcionais e degradação graciosa",
        [
            "mlflow, shap, ssqueezepy: exigem toolchain de compilação, fallback local documentado",
            "pandas.to_parquet: mesma causa raiz (pyarrow), fallback para joblib",
            "psycopg2-binary: só instalado dentro do container Docker, nunca em requirements.txt",
            "Todas as dependências validadas rodando de verdade, ver docs/03_arquitetura.md, seção 3.6",
        ],
    )

    figure_slide(prs, "Cronograma de execução: 9 meses", "gantt_chart.png")

    content_slide(
        prs, "Trilha de pesquisa interna (equipe de IA do SENAI, paralela)",
        [
            "Não faz parte do escopo contratado pelo cliente nem bloqueia nenhuma fase do cronograma acima",
            "H1-H2: modelos informados por física (physics-informed), IECON 2025, IEEE Access 2026",
            "H3, H6-H7: não/semi/auto-supervisionado para o regime real de poucos dados de falha",
            "H4: reconhecimento open-set de falhas nunca vistas (rede Siamesa + EVT)",
            "H5: predição conformal recalibrada continuamente em produção",
            "H8: Hard-Constrained Recurrent PINNs (tese de qualificação, UFSC 2026)",
            "Promovida a produção só se ganhar em robustez sem piorar interpretabilidade (ver docs/06_track_pesquisa.md)",
        ],
        subtitle="1 ML engineer adicional, meses 3-6, custeado à parte do projeto do cliente",
    )

    content_slide(
        prs, "Perguntas em aberto para o time de automação",
        [
            "Grandeza física e sensibilidade de cada sensor (vibração? corrente?)",
            "Semântica de negócio de cada uma das 5 classes",
            "Causa da coluna fantasma em Dados_1-3",
            "Disponibilidade de sinal de RPM/rotação",
            "Lista completa: docs/07_perguntas_ao_cliente.md (16 perguntas)",
        ],
    )

    prs.save(str(OUT_DIR / "Apresentacao_Tecnica.pptx"))
    print(f"wrote {OUT_DIR / 'Apresentacao_Tecnica.pptx'}")


def main() -> None:
    cfg = load_config()
    bundle = ModelBundle.load(cfg.paths.models_dir / BUNDLE_FILENAME)
    build_executive_deck(bundle)
    build_technical_deck(bundle)


if __name__ == "__main__":
    main()
