#!/usr/bin/env python3
"""Assembles Arquitetura_e_Cronograma.pdf: architecture diagram, Gantt
chart, WBS table and risk matrix -- reusing the same figures generated by
generate_deliverable_assets.py and the same content as docs/03-05.

Usage: python scripts/build_architecture_pdf.py
"""

from __future__ import annotations

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from matplotlib.image import imread

from pdm.config import REPO_ROOT

FIGURES = REPO_ROOT / "docs" / "figures"
OUT_DIR = REPO_ROOT.parent / "deliverables"
OUT_DIR.mkdir(parents=True, exist_ok=True)
OUT_PATH = OUT_DIR / "Arquitetura_e_Cronograma.pdf"

WBS = [
    ("Fase 0 (mês 1)", "Kick-off e requisitos", "Requisitos de dados assinados; acesso ao banco liberado"),
    ("Fase 1 (mês 2)", "Entendimento do domínio", "Relatório de auditoria + sensores validados"),
    ("Fase 2 (meses 3-4)", "Baseline interpretável", "Baseline aprovado pelo cliente para modo sombra"),
    ("Fase 3 (meses 4-6, paralelo)", "Pesquisa avançada", "Decisão de quais técnicas avançadas entram em produção"),
    ("Fase 4 (meses 6-7)", "Integração e piloto", "Piloto em produção-sombra por >= 30 dias sem incidentes"),
    ("Fase 5 (mês 8)", "Validação de campo", "Aceite formal do cliente para operação assistida"),
    ("Fase 6 (mês 9+)", "Acompanhamento", "Monitoramento de drift e ciclo de retrain contínuo"),
]

RISKS = [
    ("Requisitos de dados não atendidos a tempo", "Alto", "Média", "Track de pesquisa com datasets públicos em paralelo"),
    ("Sensores em campo falham/saturam/geram ruído", "Alto", "Alta", "Auditoria automática a cada novo lote (já prototipada)"),
    ("Prior de classes real difere do case (balanceado)", "Médio-Alto", "Alta", "Reavaliação sob prior configurável (já prototipada)"),
    ("Classes nunca vistas aparecem em produção", "Alto", "Média", "Track de pesquisa: open-set + conjunto conformal já sinaliza baixa confiança"),
    ("Modelo degrada com desgaste/manutenção (drift)", "Alto", "Alta", "Monitor de drift PSI+KS já prototipado"),
    ("Resistência de adoção (\"caixa preta\")", "Médio", "Média", "Árvore explicável + SHAP/LIME por predição"),
    ("Overfitting ao conjunto curado do case", "Médio", "Média", "Split com limpeza treino-only; controles de sanidade"),
    ("Latência/carga em escala de planta", "Médio", "Baixa", "Modelo raso; API stateless horizontalmente escalável"),
    ("Dependências com suporte irregular por plataforma", "Baixo-Médio", "Confirmada", "Fallback documentado; validação cruzada Windows/Linux"),
    ("Disponibilidade da equipe do cliente", "Médio", "Média", "Marcos formais de validação conjunta (M1, M2, M5)"),
]


def image_page(pdf: PdfPages, image_path, title: str) -> None:
    img = imread(image_path)
    fig, ax = plt.subplots(figsize=(11.69, 8.27))  # A4 landscape
    ax.imshow(img)
    ax.axis("off")
    ax.set_title(title, fontsize=16, weight="bold", pad=15)
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def table_page(pdf: PdfPages, title: str, col_labels: list[str], rows: list[tuple], col_widths=None) -> None:
    fig, ax = plt.subplots(figsize=(11.69, 8.27))
    ax.axis("off")
    ax.set_title(title, fontsize=16, weight="bold", pad=20)
    table = ax.table(cellText=rows, colLabels=col_labels, cellLoc="left", loc="center",
                      colWidths=col_widths)
    table.auto_set_font_size(False)
    table.set_fontsize(9)
    table.scale(1, 2.2)
    for (row, _col), cell in table.get_celld().items():
        cell.set_edgecolor("#CCCCCC")
        if row == 0:
            cell.set_facecolor("#1F3A5F")
            cell.get_text().set_color("white")
            cell.get_text().set_weight("bold")
        else:
            cell.set_facecolor("#F7F9FB" if row % 2 == 0 else "white")
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def title_page(pdf: PdfPages) -> None:
    fig, ax = plt.subplots(figsize=(11.69, 8.27))
    ax.axis("off")
    fig.patch.set_facecolor("#1F3A5F")
    ax.text(0.5, 0.62, "Arquitetura e Cronograma de Execução", ha="center", va="center",
            fontsize=28, weight="bold", color="white", transform=ax.transAxes)
    ax.text(0.5, 0.50, "Manutenção Preditiva -- Motor Elétrico", ha="center", va="center",
            fontsize=18, color="#CCD6E0", transform=ax.transAxes)
    ax.text(0.5, 0.40, "SENAI SC -- Processo Seletivo 02485/2026", ha="center", va="center",
            fontsize=14, color="#CCD6E0", transform=ax.transAxes)
    pdf.savefig(fig)
    plt.close(fig)


def main() -> None:
    with PdfPages(OUT_PATH) as pdf:
        title_page(pdf)
        image_page(pdf, FIGURES / "architecture_overview.png", "Arquitetura do sistema (visão geral)")
        image_page(pdf, FIGURES / "gantt_chart.png", "Cronograma de execução -- 9 meses")
        table_page(
            pdf, "Estrutura Analítica do Projeto (WBS)",
            ["Fase", "Entrega principal", "Marco de conclusão"],
            WBS, col_widths=[0.22, 0.32, 0.46],
        )
        table_page(
            pdf, "Matriz de Riscos e Mitigações",
            ["Risco", "Impacto", "Probabilidade", "Mitigação"],
            RISKS, col_widths=[0.33, 0.13, 0.14, 0.40],
        )
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
